---
- name: Setup Laravel Project with Docker and Kind K8s
  hosts: all
  become: yes

  vars:
    repo_url: https://github.com/Vishal2827/laravel-starter.git
    app_dir: /var/www/html/laravel-starter
    kind_version: v0.20.0
    kubeconfig_path: /root/.kube/config
    k8s_namespace: laravel

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - git
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Ensure Docker is started
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # ⬇️ ADD THESE TASKS HERE (PHP + Composer)
    - name: Install PHP and required extensions
      apt:
        name:
          - php
          - php-cli
          - php-mbstring
          - php-xml
          - php-bcmath
          - php-curl
          - php-mysql
          - php-zip
          - unzip
          - curl
          - composer
        state: present
        update_cache: yes

    - name: Ensure composer is available globally
      shell: |
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer
      args:
        creates: /usr/local/bin/composer

    - name: Install Kind
      shell: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64
        chmod +x ./kind
        mv ./kind /usr/local/bin/kind
      args:
        creates: /usr/local/bin/kind

    - name: Clone Laravel repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        force: yes

    - name: Mark repo as safe for git
      shell: git config --global --add safe.directory "{{ app_dir }}"

    - name: Create Kind cluster with config
      shell: |
        kind create cluster --name laravel --config {{ app_dir }}/laravel-k8s/kind-config.yaml --wait 60s
      args:
        creates: "{{ kubeconfig_path }}"

    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/
      args:
        creates: /usr/local/bin/kubectl


    - name: Ensure namespace exists
      shell: |
        kubectl get ns {{ k8s_namespace }} || kubectl create ns {{ k8s_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Apply Kubernetes manifests (excluding kind-config.yaml)
      shell: |
        find {{ app_dir }}/laravel-k8s/ \( -name "*.yaml" -o -name "*.yml" \) ! -name "kind-config.yaml" -exec kubectl apply -f {} \;
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"



    - name: Print Access URL YOUR SERVERS IP :30080
      shell: |
        echo "Visit Laravel at http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4):30080"
